In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier



# Load dataset
data = pd.read_csv('EasyVisa.csv')
data.head()

case_id continent education_of_employee has_job_experience  \
0  EZYV01      Asia           High School                  N   
1  EZYV02      Asia              Master's                  Y   
2  EZYV03      Asia            Bachelor's                  N   
3  EZYV04      Asia            Bachelor's                  N   
4  EZYV05    Africa              Master's                  Y   

  requires_job_training  no_of_employees  yr_of_estab region_of_employment  \
0                     N            14513         2007                 West   
1                     N             2412         2002            Northeast   
2                     Y            44444         2008                 West   
3                     N               98         1897                 West   
4                     N             1082         2005                South   

   prevailing_wage unit_of_wage full_time_position case_status  
0         592.2029         Hour                  Y      Denied  
1       83425.6500         Year                  Y   Certified  
2      122996.8600         Year                  Y      Denied  
3       83434.0300         Year                  Y      Denied  
4      149907.3900         Year                  Y   Certified

In [2]:
cate=data.select_dtypes(include=['object']).columns
label=LabelEncoder()
for col in cate:
    data[col]=label.fit_transform(data[col])

# Define features and target variable
X = data.drop('case_status', axis=1)
y = data['case_status']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


# Create the models
def machine_learning_model(model, X_train, y_train, X_test, y_test):
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Evaluate the model
    print(f"Model: {model.__class__.__name__}")

    print("----------------------------")
    print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

# Linear Regression
log_reg = LogisticRegression()
machine_learning_model(log_reg, X_train, y_train, X_test, y_test)
# Decision Tree Classifier
dec_tree = DecisionTreeClassifier() 
machine_learning_model(dec_tree, X_train, y_train, X_test, y_test)

C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Model: LogisticRegression
----------------------------
Accuracy: 0.6923076923076923
Confusion Matrix:
[[4077  184]
 [1776  333]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.96      0.81      4261
           1       0.64      0.16      0.25      2109

    accuracy                           0.69      6370
   macro avg       0.67      0.56      0.53      6370
weighted avg       0.68      0.69      0.62      6370

Model: DecisionTreeClassifier
----------------------------
Accuracy: 0.715541601255887
Confusion Matrix:
[[3364  897]
 [ 915 1194]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.79      0.79      4261
           1       0.57      0.57      0.57      2109

    accuracy                           0.72      6370
   macro avg       0.68      0.68      0.68      6370
weighted avg       0.71      0.72      0.72      6370



In [3]:
# Random Forest Classifier
rand_forest = RandomForestClassifier()
machine_learning_model(rand_forest, X_train, y_train, X_test, y_test)

Model: RandomForestClassifier
----------------------------
Accuracy: 0.78712715855573
Confusion Matrix:
[[3908  353]
 [1003 1106]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.92      0.85      4261
           1       0.76      0.52      0.62      2109

    accuracy                           0.79      6370
   macro avg       0.78      0.72      0.74      6370
weighted avg       0.78      0.79      0.78      6370

